### Register un nouvel utilisateur

POST http://localhost:3000/api/utilisateurs/register
Content-Type: application/json

{
  "nom": "Dupont",
  "prenom": "Jean",
  "email": "jean.dupont@test.com",
  "mot_de_passe": "monpassword",
  "departement": "75"
  
}

### Ajouter un commentaire à un projet
POST http://localhost:3000/api/commentaires
Content-Type: application/json

{
  "contenu": "Super projet, bon courage pour la suite !",
  "projet_id": 2,
  "utilisateur_id": 4
}


### Login pour récupérer le token JWT et le refresh token
POST http://localhost:8080/api/utilisateurs/login
Content-Type: application/json

{
  "email": "pierre.ychnightder@test.com",
  "mot_de_passe": "monpassword"
}

### Utiliser le refresh token pour obtenir un nouveau token d'accès
POST http://localhost:3000/api/utilisateurs/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJwaWVycmUueWNobmlnaHRkZXJAdGVzdC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzAwNjYxMTcsImV4cCI6MTc3MDY3MDkxN30.C1hs_6AFqzVeLahbTo6sDC9vIsmS6RPtExDi84t0hWY"
}

### Exemple d'utilisation (explications)
# 1. Faites un login pour obtenir le token et le refreshToken
# 2. Quand le token d'accès expire, appelez /refresh-token avec le refreshToken
# 3. Utilisez le nouveau token d'accès pour accéder aux routes protégées
###
POST http://localhost:3000/api/utilisateurs/logout


### Accéder au profil protégé (remplacer TOKEN par celui reçu au login)
GET http://localhost:3000/api/utilisateurs/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJwaWVycmUueWNobmlnaHRkZXJAdGVzdC5jb20iLCJyb2xlIjoiYWRtaW4iLCJub20iOiJQaWVycmUiLCJwcmVub20iOiJZY2huaWdodGRlciIsImRhdGVfaW5zY3JpcHRpb24iOiIyMDI1LTEyLTIwVDIyOjQxOjM3LjAwMFoiLCJkZXBhcnRlbWVudCI6Ijk3MyIsImlhdCI6MTc3MDA2NjEyOSwiZXhwIjoxNzcwMDY3OTI5fQ.Z1EtuhCQh_BLE3wUA-4JU7BGrSLRbbEqczxuu8x2CVw
  

### ADAMIN - Register un nouvel utilisateur avec le rôle admin

POST http://localhost:3000/api/utilisateurs/register
Content-Type: application/json

{
  "nom": "Pierre",
  "prenom": "Ychnightder",
  "email": "pierre.ychnightder@test.com",
  "mot_de_passe": "monpassword",
  "departement": "75",
  "role": "admin"
}

###
POST http://localhost:3000/api/utilisateurs/login
Content-Type: application/json

{
  "email": "pierre.ychnightder@tes.com",
  "mot_de_passe": "monpassword"
}
###

GET http://localhost:3000/api/utilisateurs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJwaWVycmUueWNobmlnaHRkZXJAdGVzdC5jb20iLCJyb2xlIjoiYWRtaW4iLCJub20iOiJQaWVycmUiLCJwcmVub20iOiJZY2huaWdodGRlciIsImRhdGVfaW5zY3JpcHRpb24iOiIyMDI1LTEyLTIwVDIyOjQxOjM3LjAwMFoiLCJkZXBhcnRlbWVudCI6Ijk3MyIsImlhdCI6MTc3MDI0MjI5NiwiZXhwIjoxNzcwMjQ0MDk2fQ.hqIwvYNjq_mBXSASTNYYqWwXDHe4TjuBTn3wh8XdHks