### Register un nouvel utilisateur

POST http://localhost:3000/api/utilisateurs/register
Content-Type: application/json

{
  "nom": "Dupont",
  "prenom": "Jean",
  "email": "jean.dupont@test.com",
  "mot_de_passe": "monpassword",
  "departement": "75"
  
}


### Login pour récupérer le token JWT
POST http://localhost:3000/api/utilisateurs/login
Content-Type: application/json

{
  "email": "pierre.ychnightder@test.com",
  "mot_de_passe": "monpassword"
}
###
POST http://localhost:3000/api/utilisateurs/logout



### Accéder au profil protégé (remplacer TOKEN par celui reçu au login)
GET http://localhost:3000/api/utilisateurs/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJwaWVycmUueWNobmlnaHRkZXJAdGVzdC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjY4OTM0MjMsImV4cCI6MTc2Njg5NDMyM30.oNSMSQnXTkvubMVAs3-I5st2ahqROjmRcVbBHZRMyh0
  

### ADAMIN - Register un nouvel utilisateur avec le rôle admin

POST http://localhost:3000/api/utilisateurs/register
Content-Type: application/json

{
  "nom": "Pierre",
  "prenom": "Ychnightder",
  "email": "pierre.ychnightder@test.com",
  "mot_de_passe": "monpassword",
  "departement": "75",
  "role": "admin"
}


###
POST http://localhost:3000/api/utilisateurs/login
Content-Type: application/json

{
  "email": "pierre.ychnightder@test.com",
  "mot_de_passe": "monpassword"
}
###